name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  VERSION: "0.1.0-${{ github.sha }}"
  BUILD_DATE: ${{ github.event.head_commit.timestamp }}
  IMAGE_REPO: "https://github.com/${{ github.repository }}"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase repository owner
        id: lowercase_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          # https://github.com/orgs/community/discussions/45969
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/osxcross-builder:${{ env.VERSION }}
            ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/osxcross-builder:latest
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            VERSION=${{ env.VERSION }}
            VCS_URL=${{ env.IMAGE_REPO }}
            VCS_REF=${{ github.sha }}
            IMAGE_URL=${{ env.IMAGE_REPO }}
          annotations: |
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ env.IMAGE_REPO }}
            org.opencontainers.image.url=${{ env.IMAGE_REPO }}
